apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster
  region: eu-central-1

vpc:
  id: vpc-0a88efbdbad938838
  cidr: "192.168.0.0/16"
  subnets:
    public:
      eu-central-1a:
        id: subnet-0bfbe5b1202e7a165
      eu-central-1b:
        id: subnet-02bdb0ef0ee05bef0
    private:
      eu-central-1a:
        id: subnet-085e1b09f3e1b6a73
      eu-central-1b:
        id: subnet-07aba7cbc1a4ca8b0

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true