apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster
  region: eu-central-1

vpc:
  id: vpc-0266bd859c1e04b22
  cidr: "192.168.0.0/16"
  subnets:
    public:
      eu-central-1a:
        id: subnet-00947415af99c52ea
      eu-central-1b:
        id: subnet-082aff5c382dcbe4e
    private:
      eu-central-1a:
        id: subnet-0f8cd1385fc233d60
      eu-central-1b:
        id: subnet-0a2899334d66f9613

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true