apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster
  region: eu-central-1

vpc:
  id: vpc-09a269fc169a715ed
  cidr: "192.168.0.0/16"
  subnets:
    public:
      eu-central-1a:
        id: subnet-02eeb95a1e2b1bd88
      eu-central-1b:
        id: subnet-040f3d72b4b7940f9
    private:
      eu-central-1a:
        id: subnet-0566836a5e91b6960
      eu-central-1b:
        id: subnet-0b9829929fa991755

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.micro
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.micro
    desiredCapacity: 1
    privateNetworking: true
    