apiVersion: v1
kind: Service
metadata:
  name: backend-service
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - nodePort: 31479
      port: 80
      targetPort: 3000