name: Build and Deploy to Docker Image
on: push
jobs:
  kubernetes-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> ${{ vars.TAG_DATE }}
      - name: Push image and deploy
        uses: observian/littleci-littlecd-eks@master
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: nextjs-application
          region: eu-central-1
          tags: ${{ vars.TAG_DATE }}
          eks_cluster_name: EKS-Demo-Cluster
          k8s_manifest: deployment1.yaml
          k8s_image_tag: ${{ vars.TAG_DATE }}
